export enum ACTION_CONST {
    GET_EXPENSES_LIST='@@EXPENSE/GET_EXPENSES_LIST',
    SET_EXPENSES_LIST='@@EXPENSE/SET_EXPENSES_LIST',
    ADD_EXPENSE_ITEM='@@EXPENSE/ADD_EXPENSE_ITEM',
    PATCH_EXPENSE_ITEM='@@EXPENSE/PATCH_EXPENSE_ITEM',
    DELETE_EXPENSE_ITEM='@@EXPENSE/DELETE_EXPENSE_ITEM',
    SET_TOTAL_COSTS='@@EXPENSE/SET_TOTAL_COSTS'
}